// Code generated by goyacc -o cpp.go cpp.y. DO NOT EDIT.

//line cpp.y:2
package parse

import __yyfmt__ "fmt"

//line cpp.y:2

import "github.com/jmhobbs/go-bicpp/ast"

//line cpp.y:10
type yySymType struct {
	yys        int
	identifier string

	integerValue int
	floatValue   float64
	stringValue  string

	node  ast.Node
	nodes []ast.Node
}

const CLASS = 57346
const IDENTIFIER = 57347
const INTEGER = 57348
const FLOAT = 57349
const STRING = 57350
const TOK_ARRAY = 57351
const TOK_BLOCK_OPEN = 57352
const TOK_BLOCK_CLOSE = 57353
const TOK_SEMICOLON = 57354
const TOK_ASSIGN = 57355
const TOK_QUOTE = 57356
const TOK_COMMA = 57357
const TOK_COLON = 57358
const TOK_DEFINE = 57359
const TOK_COMMENT = 57360

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"CLASS",
	"IDENTIFIER",
	"INTEGER",
	"FLOAT",
	"STRING",
	"TOK_ARRAY",
	"TOK_BLOCK_OPEN",
	"TOK_BLOCK_CLOSE",
	"TOK_SEMICOLON",
	"TOK_ASSIGN",
	"TOK_QUOTE",
	"TOK_COMMA",
	"TOK_COLON",
	"TOK_DEFINE",
	"TOK_COMMENT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line cpp.y:172

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 68

var yyAct = [...]int8{
	23, 5, 33, 3, 49, 16, 14, 11, 12, 11,
	12, 11, 12, 46, 44, 29, 16, 47, 40, 11,
	12, 13, 32, 13, 30, 13, 35, 38, 11, 12,
	11, 12, 16, 13, 48, 31, 22, 45, 39, 43,
	21, 16, 13, 6, 13, 20, 41, 18, 50, 37,
	36, 19, 24, 26, 27, 28, 34, 17, 4, 1,
	10, 15, 9, 8, 7, 2, 42, 25,
}

var yyPact = [...]int16{
	26, -32768, 26, 5, -32768, -32768, 52, -32768, -32768, -32768,
	-32768, 35, 27, -32768, 5, -32768, -32768, 47, -32768, 10,
	24, 47, -11, -32768, -32768, -32768, -32768, -32768, -32768, 46,
	15, 38, 37, 17, 7, 34, -32768, -32768, 47, 3,
	25, -32768, 2, -32768, 22, -32768, -8, 47, -32768, -32768,
	-32768,
}

var yyPgo = [...]int8{
	0, 67, 0, 66, 58, 65, 1, 3, 64, 63,
	62, 60, 59,
}

var yyR1 = [...]int8{
	0, 12, 12, 12, 5, 5, 7, 7, 6, 6,
	6, 6, 4, 8, 8, 8, 8, 8, 9, 10,
	11, 1, 1, 1, 2, 2, 3, 3,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 2, 1, 2, 1, 1, 1,
	1, 1, 3, 2, 7, 6, 5, 4, 4, 7,
	1, 1, 1, 1, 1, 1, 1, 3,
}

var yyChk = [...]int16{
	-32768, -12, -5, -7, -4, -6, 17, -8, -9, -10,
	-11, 4, 5, 18, -7, -4, -6, 5, 12, 16,
	10, 13, 9, -2, 5, -1, 6, 7, 8, 5,
	-7, 11, -2, 13, 10, 11, 12, 12, 10, -7,
	11, 12, -3, -2, 11, 12, 11, 15, 12, 12,
	-2,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 5, 7, 0, 8, 9, 10,
	11, 0, 0, 20, 2, 4, 6, 0, 13, 0,
	0, 0, 0, 12, 24, 25, 21, 22, 23, 0,
	0, 0, 0, 0, 0, 0, 17, 18, 0, 0,
	0, 16, 0, 26, 0, 15, 0, 0, 14, 19,
	27,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:43
		{
			file.Directives = yyDollar[1].nodes
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cpp.y:46
		{
			file.Directives = yyDollar[1].nodes
			file.Declarations = yyDollar[2].nodes
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:50
		{
			file.Declarations = yyDollar[1].nodes
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cpp.y:56
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:59
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cpp.y:65
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:68
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cpp.y:81
		{
			yyVAL.node = ast.Define{Identifier: yyDollar[2].identifier, Value: yyDollar[3].node}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cpp.y:87
		{
			yyVAL.node = ast.Class{Identifier: yyDollar[1].identifier}
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cpp.y:90
		{
			yyVAL.node = ast.Class{
				Identifier: yyDollar[1].identifier,
				Parent:     yyDollar[3].identifier,
				Body:       ast.Block(yyDollar[5].nodes),
			}
		}
	case 15:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cpp.y:97
		{
			yyVAL.node = ast.Class{
				Identifier: yyDollar[1].identifier,
				Parent:     yyDollar[3].identifier,
				Body:       ast.Block{},
			}
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cpp.y:104
		{
			yyVAL.node = ast.Class{
				Identifier: yyDollar[1].identifier,
				Body:       ast.Block(yyDollar[3].nodes),
			}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cpp.y:110
		{
			yyVAL.node = ast.Class{
				Identifier: yyDollar[1].identifier,
				Body:       ast.Block{},
			}
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cpp.y:119
		{
			yyVAL.node = ast.Assignment{
				Identifier: yyDollar[1].identifier,
				Value:      yyDollar[3].node,
			}
		}
	case 19:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cpp.y:128
		{
			yyVAL.node = ast.Assignment{
				Identifier: yyDollar[1].identifier,
				Value: ast.Array{
					Body: ast.ArrayBlock(yyDollar[5].nodes),
				},
			}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:139
		{
			yyVAL.node = ast.Comment(yyDollar[1].stringValue)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:145
		{
			yyVAL.node = ast.Integer(yyDollar[1].integerValue)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:148
		{
			yyVAL.node = ast.Float(yyDollar[1].floatValue)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:151
		{
			yyVAL.node = ast.String(yyDollar[1].stringValue)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:157
		{
			yyVAL.node = ast.Identifier(yyDollar[1].identifier)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cpp.y:164
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cpp.y:167
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[3].node)
		}
	}
	goto yystack /* stack new state and value */
}
