// Code generated by "stringer -type=DeclarationKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Assignment-0]
	_ = x[Class-1]
}

const _DeclarationKind_name = "AssignmentClass"

var _DeclarationKind_index = [...]uint8{0, 10, 15}

func (i DeclarationKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeclarationKind_index)-1 {
		return "DeclarationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeclarationKind_name[_DeclarationKind_index[idx]:_DeclarationKind_index[idx+1]]
}
