// Code generated by "stringer -type=DirectiveKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Define-0]
}

const _DirectiveKind_name = "Define"

var _DirectiveKind_index = [...]uint8{0, 6}

func (i DirectiveKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DirectiveKind_index)-1 {
		return "DirectiveKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DirectiveKind_name[_DirectiveKind_index[idx]:_DirectiveKind_index[idx+1]]
}
